- name: Uninstall servers on all nodes
  include: install/uninstallRange.yml
  vars:
    start: 0
    end: "{{ lookup('ini', 'node_init section=testConstants file=../testConstants.ini') | int -1 }}"
  
- name: Install initial version of server on Nodes.
  include: install/installRange.yml
  vars:
    start: 0
    end: "{{ lookup('ini', 'node_init section=testConstants file=../testConstants.ini') | int -1 }}"
    VER: "{{ lookup('ini', 'initial_version section=testConstants file=../testConstants.ini') | default('4.5.0') }}"
    BUILD_NO: "{{ lookup('ini', 'initial_build_no section=testConstants file=../testConstants.ini') | default(2601) }}"
    FLAVOR: "{{ lookup('ini', 'initial_flavor section=testConstants file=../testConstants.ini') | default('watson') }}"
    
- name: Initialize the cluster for first use.
  include: install/clusterinitialize.yml
  vars:
    NODES_INIT: "{{ lookup('ini', 'node_init section=testConstants file=../testConstants.ini') }}"

- name: Create travel-sample-bucket
  include: utils/initializeBucket.yml
  vars:
    NODE: "centos[0]"
    bucket_name: "travel-sample"
    bucket_ramsize: 2000

- hosts: centos[0]
  vars_files:
    - CouchbaseConstants.yml
  tasks:
  - pause: seconds=10
  - name: Create indexes for travel-sample
    include: utils/createIndexes.yml

- hosts: localhost
  vars:
    loadgen_initial_properties_file: "{{ lookup('ini', 'initial_loadgen section=loadgenerator file=testConstants.ini') }}"
    loadgen_jar_location: "{{ lookup('ini', 'loadgen_jar_location section=loadgenerator file=testConstants.ini') }}"
    loadgen_jar: "{{ lookup('ini', 'loadgen_jar section=loadgenerator file=testConstants.ini') }}"
    loadgen_sample_data: "{{lookup('ini', 'loadgen_sample_data section=loadgenerator file=testConstants.ini') }}"
    loadgen_update_properties_file: "{{ lookup('ini', 'update_loadgen section=loadgenerator file=testConstants.ini') }}"
  tasks:
  - name: Run Initial loadgen
    shell: >
      java -jar {{ loadgen_jar_location }}{{ loadgen_jar }} \ 
      --loadgen-properties {{ loadgen_initial_properties_file }} \ 
      --sample-data-file {{ loadgen_jar_location }}{{ loadgen_sample_data }} > /tmp/initial_loadgen.log 2>&1
   
  - name: Run update loadgen
    shell: >
      java -jar {{ loadgen_jar_location }}{{ loadgen_jar }} \ 
      --loadgen-properties {{ loadgen_update_properties_file }} \ 
      --sample-data-file {{ loadgen_jar_location }}{{ loadgen_sample_data }} > /tmp/update_loadgen.log 2>&1  &

- hosts: centosupgradenode[0]
  vars:
    node: centosupgradenode[0]
    VER: "{{ lookup('ini', 'upgrade_version section=testConstants file=../testConstants.ini') | default('5.0.0') }}"
    BUILD_NO: "{{ lookup('ini', 'upgrade_build_no section=testConstants file=../testConstants.ini') | default(3358) }}"
    FLAVOR: "{{ lookup('ini', 'upgrade_flavor section=testConstants file=../testConstants.ini') | default('spock') }}"
    ver_no: "{{VER|default('4.5.0')}}"
    build_no:  "{{BUILD_NO|default(2601)}}"
    flavor:  "{{FLAVOR|default('watson')}}"
    base_url:  http://172.23.120.24/builds/latestbuilds/couchbase-server/{{flavor}}/
    build_pkg: "couchbase-server-enterprise-{{ver_no}}-{{build_no}}-centos6.x86_64.rpm"
    url_var: "{{base_url}}/{{build_no}}/{{build_pkg}}"
    build_url: "{{URL|default(url_var)}}"
    rpm_path: "/tmp/couchbase.rpm"
  tasks: 
  - name: Uninstall couchbase on swap node
    include: install/uninstallTasks.yml

  - name: Install upgrade version on Swap node
    include: install/installTasks.yml

- name: Upgrade cluster
  include: upgrade/onlineUpgradeClusterByFreshInstall.yml
  vars:
    start: 0
    end: "{{ lookup('ini', 'node_init section=testConstants file=../testConstants.ini') | int - 1}}"
    VER: "{{ lookup('ini', 'upgrade_version section=testConstants file=../testConstants.ini') | default('5.0.0') }}"
    BUILD_NO: "{{ lookup('ini', 'upgrade_build_no section=testConstants file=../testConstants.ini') | default(3358) }}"
    FLAVOR: "{{ lookup('ini', 'upgrade_flavor section=testConstants file=../testConstants.ini') | default('spock') }}"

- name: run updated sdk application
  vars:
    loadgen_updated_properties_file: "{{ lookup('ini', 'updated_loadgen section=loadgenerator file=testConstants.ini') }}"
    loadgen_jar_location: "{{ lookup('ini', 'loadgen_jar_location section=loadgenerator file=testConstants.ini') }}"
    loadgen_jar: "{{ lookup('ini', 'updated_loadgen_jar section=loadgenerator file=testConstants.ini') }}"
    loadgen_sample_data: "{{lookup('ini', 'loadgen_sample_data section=loadgenerator file=testConstants.ini') }}"
    loadgen_update_properties_file: "{{ lookup('ini', 'update_loadgen section=loadgenerator file=testConstants.ini') }}"
  tasks:
  - name: Run loadgen
    shell: >
      java -jar {{ loadgen_jar_location }}{{ loadgen_jar }} \
      --loadgen-properties {{ loadgen_updated_properties_file }} \
      --sample-data-file {{ loadgen_jar_location }}{{ loadgen_sample_data }} > /tmp/updated_loadgen.log 2>&1 &
